name: Deploy to GitHub Pages

on:
  # Run on push to any branch
  push:
    branches: ['**']
  # Allow manual workflow trigger
  workflow_dispatch:

# Permissions needed for deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Install, build, and upload your site
        uses: withastro/action@v3
        # Optional:
        # with:
        #   path: . # Root of your Astro project
        #   node-version: 20
        #   package-manager: pnpm@latest

  deploy:
    # Only deploy if the push was to the `master` branch
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
